*******************************
******* Initial states  *******
*******************************

omod INITIAL-STATES is 
    including RBC .
    
    ops TP1 TP2 OBU1 OBU2 RBC1 TC1 TC2 
        GoodDriver1 GoodDriver2 : -> Oid .
        *** Actually a "monkey driver"

    op X : -> NNegRat .
    op shift : -> NNegRat .

    eq sbThreshold = 3550/36 .
    eq ebThreshold = 100 .


    *** Initial states used for executing model.
    ops init1 initWithDriver initTwoTrainsWithDrivers
        initWithDriverOptimalConst : -> GlobalSystem .

    eq init1 = {
        eoaMA(1, 40000)
        < 1 : Train | position : 0, velocity : 0, eoa : 0,
            trainComponents : 
                < TP1 : TrainPlant | currentState : accelerating  >
                < OBU1 : OnBoardUnit | obuTimer : deltaOBU, lastMsg : dummy >
                < TC1 : TrackComputation | timerTC : deltaTC, oldTrack : Entry >
        >
        < RBC1 : RBC | occupiedTracks : (Entry |-> true), trainPositions : (1 |-> Entry) >
    } .

    eq initWithDriver = {
        eoaMA(1, 629)
        < 1 : Train | position : 0, velocity : 0, eoa : 0,
            trainComponents : 
                < GoodDriver1 : Driver | timer : deltaDriver >
                < TP1 : TrainPlant | currentState : accelerating  >
                < OBU1 : OnBoardUnit | obuTimer : deltaOBU, lastMsg : dummy >
                < TC1 : TrackComputation | timerTC : deltaTC, oldTrack : Entry >
        >
        < RBC1 : RBC | occupiedTracks : (Entry |-> true), trainPositions : (1 |-> Entry) >
    } .

    eq initWithDriverOptimalConst = {
        < 1 : Train | position : 0, velocity : 70, eoa : 44784,
            trainComponents : 
                < TP1 : TrainPlant | currentState : coasting > 
                < OBU1 : OnBoardUnit | obuTimer : deltaOBU, lastMsg : dummy >
                < TC1 : TrackComputation | timerTC : deltaTC, oldTrack : Entry >
        >
        < RBC1 : RBC | occupiedTracks : (Entry |-> true), trainPositions : (1 |-> Entry) >
    } .

    eq initTwoTrainsWithDrivers = {
        eoaMA(1, 629)
        < 1 : Train | position : 0, velocity : 0, eoa : 0,
            trainComponents : 
                < GoodDriver1 : Driver | timer : deltaDriver >
                < TP1 : TrainPlant | currentState : accelerating  > 
                < OBU1 : OnBoardUnit | obuTimer : deltaOBU, lastMsg : dummy >
                < TC1 : TrackComputation | timerTC : deltaTC, oldTrack : Entry >  
        >
        < 2 : Train | position : 0, velocity : 0, eoa : 0, 
            trainComponents : 
                < GoodDriver2 : Driver | timer : deltaDriver >
                < TP2 : TrainPlant | currentState : stopped > 
                < OBU2 : OnBoardUnit | obuTimer : deltaOBU + shift, lastMsg : dummy >
                < TC2 : TrackComputation | timerTC : deltaTC + shift, oldTrack : Entry >
        >
        < RBC1 : RBC | occupiedTracks : (Entry |-> true), trainPositions : (1 |-> Entry, 2 |-> Entry) >
    } . 
endom