*******************************
***** Radio Block Center  *****
*******************************

view Track from TRIV to TRACK is
    sort Elt to Track .
endv

omod RBC is
    protecting TRACKCOMPUTATION .
    *** * here is renaming 
    protecting MAP{Track,Bool} * (sort Map{Track,Bool} to MapTrack2Bool) .
    protecting MAP{Oid,Track} * (sort Map{Oid, Track} to MapTrain2Track) .

    class RBC | occupiedTracks : MapTrack2Bool, trainPositions : MapTrain2Track .

    vars TRK1, T2 : Track .
    *** If a train is occupying track `TRK` then 
    *** `OCCMAP[TRK] = true`, otherwise `OCCMAP[TRK] = false`.  
    var OCCMAP : MapTrack2Bool .
    var N : Nat .
    *** If a train with the id `ID` is on track `TRK` then 
    *** `OCCMAP[ID] = TRK`,
    *** otherwise... what? Some sort of undefined?
    var POSMAP : MapTrain2Track .
    vars O1 O2 O3 O4 O5 O6 : Oid .
    var T : Time .


    op maxTrainID : -> Nat .

    *** Train IDs are numbers.
    *** Why is this defined here and not in
    *** train module?
    subsort Nat < Oid .

    *** 0 <= freeTracksAhead <= 5
    op freeTracksAhead : Track MapTrack2Bool -> Nat .

    *** No free tracks ahead if track is exit 
    *** Or if next track is occupied.
    ceq freeTracksAhead(TRK1, OCCMAP)
        = 0 
            if ((TRK1 == Exit) or OCCMAP[next(TRK1)] == true) .

    *** Recursively compute free tracks ahead
    *** -- maximum 5 though.
    ceq freeTracksAhead(TRK1, OCCMAP)
        = min(5, (1 + freeTracksAhead(next(TRK1), OCCMAP)))
            if TRK1 =/= Exit .

    *** Determines how many tracks ahead a 
    *** train can move from a given track.
    *** I.e, the movement authority is the 
    *** track that is N tracks ahead.
    op computeMA : Track Oid -> Nat .

    eq computeMA(TRK1, 0) = end(TRK1) .
    eq computeMA(TRK1, 1) = end(next(TRK1)) .
    ceq computeMA(TRK1, N) = computeMA(next(TRK1), N - 1) if N > 1 .

    *** Passage of time does not affect `RBC`.
    eq mte(< O1 : RBC | >) = INF .

    *** The `delta` of the `RBC` class
    *** does nothing.
    eq delta(< O1 : RBC | >, T)
        = < O1 : RBC | > .
    
    *** Consider updating these rule to consume 
    *** updateChange always -- or when train is at 
    *** the end.

    *** Last train, but not on exit.
    crl [lastTrainNotExit] :
        updateChange(O1, T2)
        < O2 : RBC | occupiedTracks : OCCMAP, trainPositions : POSMAP >
        => 
        eoaMA(maxTrainID,
                computeMA(T2, 
                          freeTracksAhead(T2, insert(T2, true, insert(prev(T2), false, OCCMAP)))))
        < O2 : RBC | occupiedTracks : insert(T2, true, insert(prev(T2), false, OCCMAP)),
                     trainPositions : insert(maxTrainID, T2, POSMAP)
        >
        if T2 =/= Exit and O1 == maxTrainID .

    *** Not last train, but not on exit.
    crl [notLastOnExit] : 
        updateChange(O1, Exit)
        < O2 : RBC | occupiedTracks : OCCMAP, trainPositions : POSMAP >
        => 
        eoaMA(O1 + 1, 
            computeMA(POSMAP[O1 + 1], 
                      freeTracksAhead(POSMAP[O1 + 1], insert(Exit, true, insert(prev(Exit), false, OCCMAP)))))
        < O2 : RBC | occupiedTracks : insert(Exit, true, insert(prev(Exit), false, OCCMAP)),
                     trainPositions : insert(O1, Exit, POSMAP)
        >
        if O1 < maxTrainID . 

    *** Not last train and not on exit.
    crl [updateMovementAuthority] :
        updateChange(O1, T2)
        < O2 : RBC | occupiedTracks : OCCMAP, trainPositions : POSMAP >
        => 
        eoaMA(O1, computeMA(T2, 
                            freeTracksAhead(T2, insert(T2, true, insert(prev(T2), false, OCCMAP)))))
        eoaMA(O1 + 1, 
              computeMA(POSMAP[O1 + 1], 
                        freeTracksAhead(POSMAP[O1 + 1], insert(T2, true, insert(prev(T2), false, OCCMAP)))))
        < O2 : RBC | occupiedTracks : insert(T2, true, insert(prev(T2), false, OCCMAP)),
                     trainPositions : insert(O1, T2, POSMAP)
        >
        if O1 < maxTrainID and T2 =/= Exit .
endom
